---
title: 'STA2453 - Lab #3'
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Due Date: Tuesday, Oct. 29, 9:30

Use `R` to answer the questions below.  Submit your answers in an R Markdown document along with a PDF export of the R Markdown. 

# Question 1

  (a) Create the full data set (i.e., the unit of analysis is the patient) used in Charig et al (`r emo::ji("scroll")`), and compare the success of open versus percutaneous surgery using logistic regression and contingency tables.  Which surgical procedure has a higher success rate? Briefly explain.
   (b) Compare the success rates of open versus percutaneous in the $< 2 \text { cm}$, and $\geq 2 \text{ cm}$ separately using logistic regression and contingency tables.  Which surgical procedure has a higher success rate? Briefly explain.
   (c) Use (a) to (b) to develop a conclusion about which surgical procedure has a higher success rate? Briefly explain.

(`r emo::ji("scroll")`) [Charig, Clive R., et al. "Comparison of treatment of renal calculi by open surgery, percutaneous nephrolithotomy, and extracorporeal shockwave lithotripsy." Br Med J (Clin Res Ed) 292.6524 (1986): 879-882.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1339981/)

# Question 2

Statistical Society of Canada Case Study 2 (2019).  The data and background are available [here](https://ssc.ca/en/case-study/case-study-2-risk-cardiovascular-disease-among-osteoarthritis-patients). 

(a) Develop answers to 1,2, and 4. 

(b) Evaluate the predictive accuarcy of the model used to calculate the adjusted measure of association between osteoarthitis and  heart disease. Do you recommend using this model to prdedict heart disease for Canadians? 

