---
title: 'Project #3 Mock Consultation'
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Background

Throughout this course we have completed some fancy analyses, and worked hard on presenting those results verbally (project #1) and through visualizations (project #2). For this project, we are going work on an unheralded but equally important skill:  consulting with a client/collaborator at the outset of a project.

As data scientists we are often brought into a project during its design stage (hopefully!). Potential clients/collaborators come to us from a variety of technical (or non-technical) backgrounds looking for help. Depending on their level of expertise, they may only have a vague idea of the types of exciting skills and abilities you bring to the table. They've often been told, "Maybe you should talk to a statistician". This will innevitably lead to an initial meeting with you, the expert data scientist, to discuss their project, its goals, and how you can help. 

The primary goal of this project is to gain some experience in one of these early meetings. We will do this through a mock consultation session. This will be a 20-25 minute meeting where a mock client (me and/or a colleague) will sit with you, describe their company and a couple of issues they need help with. 

It will be your aim to try to distill what the client needs and how you can help. You will need to ask questions to understand their problems, available data sources, and any restrictions on potential solutions. Please refer to the lecture on consulting for the types of questions you may want to ask.

## The Problem

The client has sent you the following email asking for help:

> Dear Math Person,
>
> Thank you so much for agreeing to meet with me next week. Prior 
> to our  meeting I wanted to give you a little background
> on my company and the problem we are working on. 
>
> WhatNow provides our customers with pre-packaged date nights, 
> where each item on the date's itinerary is revealed shortly
> before it begins. The people participating in one of our
> date nights is looking for adventure, and is excited by
> the mystery of our date packages.
>
> Our dates are made up of a series of mini events. For example a 
> wine tasting, followed by a dinner at a restaurant, 
> followed by an art class. 
>
> We have been running our service for the past 2 months
> collecting data on customer demographics as well
> as a survey after using one of our dates. We are interested
> in trying to predict which date package a potential 
> customer would enjoy. 
>
> We are also trying to determine if our customers enjoy
> the mystery portion of the date night (i.e. not knowing
> anything about the date until it happens) vs. one person 
> knowing the itinerary while their date is blinded, vs
> all people on the date knowing the itinerary ahead of time.
> We have tried running several of our dates under these scenarios
> and would like to know which one is best. 
>
> Thanks again for agreeing to help out.
>
> Sandeep


## Deliverables

You have been divided into groups of 2, and one group of 3. Grades will be given based on your mock consultation (40%), and a short 5 page write-up (60%). The consultation sessions will take place between April 1st and April 8th. The write-up will be due in 2 weeks after the consultation session.

### The mock consultation session

You will meet for 20-25 minutes to get more information about
the project and to ask any clarifying questions you might have. Your mock consultation grade will be broken up as follows: 

- Professionalism (25%)
  -Listen to the client. Don't speak over the client. Be curtious 
- Communication (25%)
  - Does the client understand your questions and anything you are proposing
  - TIP: restate things in your own words to see if the client agrees
- Are you able to get at what the client trully wants/needs (25%)
  - By the end of the meeting it should be clear what the client is asking of you and what you will be delivering
- Gain insight into the data the client has available (25%)
  - Do you understand what data sources are available?
  - How much data?
  - Are there any key variables
  - What is the unit of analysis?



# The Write-up

After the consultation session, I am going to provide you with a sample of data related to the problem. It won't be a complete dataset intended to be analyzed. The purpose is to guide questions for the next meeting. You will have 2 weeks after the session to hand in a 5 page write-up which has the following sections


- Session Review (25%): What did you think of the mock session? What do you think went well? What do you think could have gone better? 
- Preparing for next session (25%): What additional information do you need? What additional questions do you have after looking at the sample data? 
- Proposed Analysis (35%): What is your plan of attack to solve the problem. What methodological approach will you take?
- Deliverables and timeline(15%): What will you be delivering to the client, and how long do you estimate it will take?





